parserPreset: conventional-changelog-conventionalcommits

rules:
  body-leading-blank:
    - 1
    - always
  body-max-line-length:
    - 2
    - always
    - 100
  header-max-length:
    - 2
    - always
    - 100
  header-min-length:
    - 2
    - always
    - 10
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - style
      - refactor
      - perf 
      - test
      - build
      - ci
      - chore
      - revert