services:
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment: 
      DATABASE_URL: postgresql+asyncpg://postgres:testpass@db:5432/bookly
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bookly
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery:
    build: .
    command: celery -A src.celery_tasks.c_app worker --loglevel=INFO
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:testpass@db:5432/bookly
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge