name: Conventional Commits Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install @commitlint/cli @commitlint/config-conventional --save-dev

      - name: Create commitlint config
        run: |
          echo "{
            \"extends\": [\"@commitlint/config-conventional\"]
          }" > .commitlintrc.json

      - name: Conventional Commits Check
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.json
          failOnWarnings: false
          commitDepth: 1