name: Nightly Build

on:
  schedule:
    - cron: '0 8 * * *'  # Midnight PST
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: bookly
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y psycopg2-binary
          pip install -r requirements.txt
          pip install pytest pytest-asyncio asyncpg
      
      - name: Run Tests
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:testpass@localhost:5432/bookly
          JWT_SECRET: test_secret_key
          JWT_ALGORITHM: HS256
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_URL: redis://localhost:6379/0
          MAIL_USERNAME: ${{ env.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ env.MAIL_PASSWORD }}
          MAIL_SERVER: smtp.ethereal.email
          MAIL_PORT: 587
          MAIL_FROM: noreply@test.com
          MAIL_FROM_NAME: Test System
          DOMAIN: localhost
        run: |
          python -m pytest --asyncio-mode=strict
          
      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        if: success()
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GITHUB_TOKEN }}
          
      - name: Convert Repository Name to Lowercase
        id: repo-name
        run: |
          echo "REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Container
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}:nightly
            ghcr.io/${{ env.REPO_LOWER }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          
      - name: Send Email Notification on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: ${{ env.MAIL_USERNAME }}
          password: ${{ env.MAIL_PASSWORD }}
          subject: "Nightly Build Failed"
          to: ${{ env.NOTIFICATION_EMAIL }}
          body: |
            The nightly build failed.
            
            Commit: ${{ github.sha }}
            Repository: ${{ github.repository }}
            
            Please check the GitHub Actions logs for more details:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          from: CI System